### ISSUE TITLE
Globe locked up after rapid zoom action with mouse wheel

### ISSUE THREAD

**Issue by emxsys** [emxsys/explorer.worldwind.earth#2]
Console Errors:

```
worldwindlib.20160721.js:72 WorldWindow.redrawIfNeeded: Exception occurred during redrawing.
ArgumentError: Matrix.multiplyByLookAtModelview: Range is less than zero
Error
    at t.e (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:72:11766)
    at Float64Array.h.multiplyByLookAtModelview (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:74:1554)
    at l.EnhancedLookAtNavigator.intermediateState (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/EnhancedLookAtNavigator.js:235:23)
    at l.EnhancedLookAtNavigator.validateEyePosition (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/EnhancedLookAtNavigator.js:201:39)
    at l.EnhancedLookAtNavigator.applyLimits (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/EnhancedLookAtNavigator.js:149:23)
    at l.E.currentState (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:94:1493)
    at y.resetDrawContext (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:98:260)
    at y.redrawIfNeeded (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:97:31468)
    at y.animationFrameLoop (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:97:31159)
    at t (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:97:31133)log @ worldwindlib.20160721.js:72
worldwindlib.20160721.js:72 Matrix.multiplyByLookAtModelview: Range is less than zerolog @ worldwindlib.20160721.js:72
worldwindlib.20160721.js:74 Uncaught ArgumentError: Matrix.multiplyByLookAtModelview: Range is less than zero
Error
    at t.e (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:72:11766)
    at Float64Array.h.multiplyByLookAtModelview (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:74:1554)
    at l.EnhancedLookAtNavigator.intermediateState (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/EnhancedLookAtNavigator.js:235:23)
    at l.EnhancedLookAtNavigator.validateEyePosition (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/EnhancedLookAtNavigator.js:201:39)
    at l.EnhancedLookAtNavigator.applyLimits (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/EnhancedLookAtNavigator.js:149:23)
    at l.E.currentState (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:94:1493)
    at y.resetDrawContext (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:98:260)
    at y.pick (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/libs/emxsys/worldwindlib.20160721.js:97:29455)
    at SelectController.handlePick (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/SelectController.js:118:33)
    at Array.<anonymous> (http://localhost:2489/Emxsys-World%20Wind%20Explorer/root/js/model/globe/SelectController.js:54:22)
```

**Comment by emxsys** [comment]
try/catch needed

**Comment by emxsys** [comment]
Seems to have been resolved.
